# Generated by Django 5.0.14 on 2025-07-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="date_of_birth",
            field=models.DateField(blank=True),
        ),
    ]
