# Generated by Django 5.0.14 on 2025-07-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0002_alter_voter_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
